name: annotated_facade_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  build: ^1.6.2
  source_gen: ^0.9.10
  annotated_facade:
    git:
      url: https://github.com/severgroup-tt/annotated_facade.git
      ref: master

dev_dependencies:
  build_test: ^1.3.6
  build_runner: ^1.11.1
  test: ^1.15.7
