name: annotated_facade_generator
description: A new Flutter package.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.1.0
  source_gen: ^1.0.0
  annotated_facade:
    git:
      url: https://github.com/severgroup-tt/annotated_facade.git
      ref: master

dev_dependencies:
  build_test: ^2.1.3
  build_runner: ^2.1.1
  test: ^1.17.10
