name: annotated_facade_generator
description: A new Flutter package.
version: 0.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  build: ^2.0.0
  source_gen: ^0.9.10+3
  annotated_facade:
    git:
      url: https://github.com/severgroup-tt/annotated_facade.git
      ref: master

dependency_overrides:
  build: ^2.0.0

dev_dependencies:
  build_test: ^2.0.0
  build_runner: ^1.12.1
  test: ^1.16.8
